### ISSUE TITLE
Notify should return option type

### ISSUE THREAD

**Issue by timohanke** [research-ag/motoko-lib#52]
https://github.com/research-ag/motoko-lib/blob/91d3480b1d4f2888286119003eec1762ce4dc317/src/TokenHandler.mo#L312-L313

If we cannot obtain a lock then we must return null. That way the user knows that he should try again later.

**Comment by AndyGura** [comment]
Fixed: https://github.com/research-ag/motoko-lib/commit/ab67bce50c636e97169e4a4b62ba485b77101715
